// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditorLayout: typeof import('./src/components/EditorLayout/EditorLayout.vue')['default']
    EditorLeft: typeof import('./src/components/EditorLayout/EditorLeft.vue')['default']
    EditorRight: typeof import('./src/components/EditorLayout/EditorRight.vue')['default']
    HeaderBar: typeof import('./src/components/Header/HeaderBar.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
